#! /usr/bin/python

__author__ = 'philipp'
__dateOfCreation__ = '9/12/12'
import os
import sys
import getopt

import easygui as eg

import urllib
import subprocess

def process(arg):
    try:
        _search_term = urllib.quote(arg)
        os.system("nohup google-chrome --app http://thesaurus.com/browse/%s > /dev/null 2>&1&"%_search_term)
    except Exception as e:
        print "There was an exception:"
        print e




def main():
# parse command line options
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
    except getopt.error, msg:
        print msg
        print "for help use --help"
        sys.exit(2)
        # process options
    for o, a in opts:
        if o in ("-h", "--help"):
            print __doc__
            sys.exit(0)
            # process arguments

    inputs = "".join([arg for arg in args])
    print inputs
    process(inputs)# process() is defined elsewhere


if __name__ == "__main__":
    main()


